---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/amazinglaundryapp.com
    - /bin/cp -R public/build $DEPLOYPATH/public/
    - /usr/local/bin/php $DEPLOYPATH/artisan config:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan view:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan cache:clear
